import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className="w-full bg-[#F5F5F7] flex flex-col items-center ">
        <div className="w-full flex justify-center bg-cyan-900">
          <Header />
        </div>

        {children}
      </body>
    </html>
  );
}
